### ISSUE TITLE
error

### ISSUE THREAD

**Issue by T8mars** [sebord/ComfyUI-LMCQ#8]
![image](https://github.com/user-attachments/assets/744b05c9-dc05-4856-852a-3c303e042705)

更新后pyarmor这个库报错，有安装，是需要哪个版本吗
![image](https://github.com/user-attachments/assets/20503ac0-0fb1-4cbb-9d89-291a087cb086)

**Comment by sebord** [comment]
9.0.6，当然9.0.7应该也可以，我待会儿同步更新一下

**Comment by sebord** [comment]
现在可以拉取代码，我把pyarmor加入进去了
